spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3333/school
    username: root
    password: root
server:
  port: 8001
microservice:
  student: http://localhost:8002
---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/school
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
microservice:
  student: ${STUDENT_URL}
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:school
    username: sa
    password:
microservice:
  student:


# mvn test -Dspring.profiles.active=test
# mvn clean install -DskipTests -Dspring.profiles.active=prod
